require("serhii.plugins-setup")
require("serhii.core.options")
require("serhii.core.keymaps")
require("serhii.plugins.fzf-lua")
require("serhii.core.colorscheme")
require("serhii.plugins.nvim-tree")
require("serhii.plugins.nvim-cmp")
require("serhii.plugins.treesitter")
require("serhii.plugins.treesitter-context")
require("serhii.plugins.treesj")
require("serhii.plugins.lsp")
require("serhii.plugins.comment")
require("serhii.plugins.indent-blankline")
require("serhii.plugins.gitsigns")
require("serhii.plugins.spectre")
require("serhii.plugins.fugitive")
require("serhii.plugins.harpoon")
require("serhii.plugins.luasnip")
-- require("serhii.plugins.autopairs")
-- require("serhii.plugins.bufferline")
